export const UPDATE_COMPONENTS = 'BUILDER/UPDATE_COMPONENTS';
export const SET_ACTIVE_ITEM = 'BUILDER/SET_ACTIVE_ITEM';
export const START_DRAGGING = 'BUILDER/START_DRAGGING';
export const END_DRAGGING = 'BUILDER/END_DRAGGING';
