export const SET_ACTIVE_ITEM = 'BUILDER/SET_ACTIVE_ITEM';
export const SELECT_ACTIVE_ITEM = 'BUILDER/LOAD_ACTIVE_ITEM';
export const START_DRAGGING = 'BUILDER/START_DRAGGING';
export const END_DRAGGING = 'BUILDER/END_DRAGGING';
