export const OPEN_DRAWER = 'DRAWER/OPEN';
export const CLOSE_DRAWER = 'DRAWER/CLOSE';
export const SET_DRAWER_FILTER = 'DRAWER/SET_DRAWER_FILTER';
export const LOAD_DRAWER_COMPONENTS = 'DRAWER/LOAD_DRAWER_COMPONENTS';
